Lugo 114
lugobots/lugo4node pull request #16
Opened 2024-01-13 22:01 UTC by mauriciorobertodev

Cria o GameSnapshotInspector e altera o bot de exemplo pra usar ele

2024-01-27 18:44 UTC, rubens21 commented on src/client.ts
> +                                        orderSet.setOrdersList(botReturn);
@mauriciorobertodev , pq o valor retornado pode ser um array?

2024-01-27 18:46 UTC, rubens21 commented on example/typescript/src/myBot.ts
> +    private makeReader(snapshot: GameSnapshotInspector): {  me: Lugo.Player } {
não precisa do reader mais, o snapshot tem um methodo getMe

2024-01-27 18:52 UTC, rubens21 commented on src/client.ts
> +                                        orderSet.setOrdersList(botReturn);
deixa quieto, saquei

2024-01-27 18:54 UTC, rubens21 commented on src/game-snapshot-inspector.ts
> +    getMe(): Lugo.Player | null {
esse método nao pode retornar null. O contstrutor da pau quando o jogador não tá no snapshot.

2024-01-27 18:54 UTC, rubens21 commented on src/game-snapshot-inspector.ts
> +	getPlayer(side: Lugo.Team.Side, number: number): Lugo.Player | null {
formatar arquivo

2024-01-27 19:12 UTC, rubens21 commented on src/game-snapshot-inspector.ts
> +    getMyGoal(): Goal {
Antigamente os metodos   getOpponentGoal e   getMyGoal costumava ficar no reader, mas eu acho meio confuso ter coisas estáticas (coisas que nao sao afetdas pelo game snapshot) no snapshot inspector.

No projeto em Go, eu movi esses metodos para o Mapper. Então tudo relacionado ao campo (regioes, mapa, lado, etc, ) fica no mapper.

Além disso, pode ficar confuso para o programador se "my goal" quer dizer "goal onde eu denovo chutar" ou "o gol do mey time".

PRa resolver isso, na versão em Go eu mudei esses nomes para `GetDefenseGoal` e `GetAttackGoal` (https://github.com/lugobots/lugo4go/blob/v3-simplifying-client/field/mapper.go#L148) 

Segue esse padrão por favor, e me diz o que vc acha disso

2024-01-27 19:14 UTC, rubens21 requested changes
Bom trabalho, @mauriciorobertodev ! esse mudanca afeta muita coisa e na base, e o PR só recebeu alguns comentários e solicitoes de ajustes.

2024-01-29 13:39 UTC, mauriciorobertodev commented on src/game-snapshot-inspector.ts
> +    getMyGoal(): Goal {
pra mim nunca passou na minha cabeça que getMyGoal era pra pegar o gol objetivo mas entendo por que fez isso

2024-01-29 13:40 UTC, mauriciorobertodev commented on src/game-snapshot-inspector.ts
> +	getPlayer(side: Lugo.Team.Side, number: number): Lugo.Player | null {
não entendi o que é pra mim formatar aqui

2024-02-03 17:16 UTC, merged