Lugo 117 -  simplifica o main
lugobots/lugo4node pull request #17
Opened 2024-01-18 23:34 UTC by mauriciorobertodev

2024-01-27 19:26 UTC, rubens21 requested changes

2024-01-27 19:26 UTC, rubens21 commented on example/typescript/src/main.ts
> -const myBot = new MyBot(
colocar um exemplo de como trocar a posicão inicial.

2024-01-27 19:26 UTC, rubens21 commented on src/starter.ts
> +export function NewDefaultStarter() {
repare que aqui tem uma diferenća importante em relacao ao formato feito no projeto em Go.

Aqui o "starter" cria o client assim que o starter é criado, então a posicão inicial já está finida e o dev não vai poder mudar isso no main.

Lá no Go, o starter não cra o client imediatamente, O dev precisa chamar o `Run` pra comećar. Então dá tempo de trocar qq coisa no main.

Ao invés de retornar a funcao `playAsBot`, precisa passar as funcoes:

`Run` 
`RunJustTurnHandler`

Essas funcoes vao então criar o client.
https://github.com/lugobots/lugo4go/blob/v3-simplifying-client/starter.go#L14

2024-01-29 15:27 UTC, mauriciorobertodev commented on src/starter.ts
> +export function NewDefaultStarter() {
![image](https://github.com/lugobots/lugo4node/assets/75261537/ec2a825c-7213-4110-8315-8de6a859dc99)

2024-02-03 17:21 UTC, merged